# Generated by Django 6.0.2 on 2026-04-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='name',
        ),
        migrations.AddField(
            model_name='cuenta',
            name='account_number',
            field=models.CharField(default=123456, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='type_trx',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=20),
        ),
    ]
