# Generated by Django 6.0.2 on 2026-04-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_remove_cliente_name_cuenta_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='dni',
            field=models.CharField(default=16367873, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
