# Generated by Django 6.0.2 on 2026-04-04 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_cliente_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='destination_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_entrantes', to='gestion.cuenta'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='source_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_salientes', to='gestion.cuenta'),
        ),
    ]
