# Generated by Django 6.0.2 on 2026-04-07 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_transaccion_destination_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='currency',
        ),
        migrations.AddField(
            model_name='cuenta',
            name='account_type',
            field=models.CharField(choices=[('VISTA', 'Vista'), ('AHORRO', 'Ahorro'), ('CORRIENTE', 'Corriente')], default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='type_trx',
            field=models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=20),
        ),
    ]
